### ISSUE TITLE
Serve the tool via GitHub Pages

### ISSUE THREAD

**Issue by eckes** [JoernMueller/Ice-Ed#3]
You can enable GitHub Pages in the project settings.

I have done this for my fork, so the repo root is available:

![image](https://user-images.githubusercontent.com/679793/92322623-94944f00-f032-11ea-9895-1bff7c3e2117.png)

Now you can access the tool via https://eckes.github.io/Ice-Ed/IceEd.html; no need to download anything.

Another advantage is that the file is directly served from the `main` branch, so users always access an up-to-date version!

More information: https://pages.github.com/

**Comment by JoernMueller** [comment]
Since your hint on GSV forum last week the tool is also accessible via this [repo](https://joernmueller.github.io/Ice-Ed/IceEd.html). So if there is an issue with it I would ask you to please elaborate further on it as I don´t get it.
This GitHube Page also is still delivered from the main branch. But from my experience just pushing out the latest commit is not very advisable, because the handling of bug reports without having tagged revisions is likely to get nasty.

Another reason why I´m still somewhat inconclusive in regards of hosting the tool is the handling of the ingredients database. There is a limited number ingredients I ship with the tool, but I´m probably not going to extend it very much further. So users will be required to add or adjust this data according to their needs. And while they of course can im/export all their stuff this is a bit tedious. This is why I added the Download option to the tool that stores a self-modified version of the html file containing the current database and my prefered approach would be a rather community based distribution where folks just share and pass on the tool with all their additions to create a comprehensive collection of ingredients on the long run. But it seems that it will get hard to perpetuate this approach since it conflicts with the way people are commonly used to use websites.

**Comment by eckes** [comment]
Uh, didn't notice it's already available, so I'll close the issue.

Regarding pushes to main: the main branch should of course always provide a stable version. This can easily be achieved with a feature-branch based workflow:

https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow
